In [2]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.optimizers import Adam

In [8]:
iris_data = load_iris()
features = iris_data.data
labels = iris_data.target.reshape(-1, 1)

In [10]:
encoder = OneHotEncoder()
targets = encoder.fit_transform(labels).toarray()
print(targets)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [11]:
train_features, test_features, train_targets, test_targets = train_test_split(features, targets, test_size=0.3)

In [12]:
model = Sequential()
model.add(Dense(10, input_dim=4, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))

In [18]:
optimizer = Adam(learning_rate=0.001)
model.compile(loss='categorical_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])
model.fit(train_features, train_targets, epochs=10000, batch_size=20, verbose=2)
results = model.evaluate(test_features, test_targets, use_multiprocessing=True)

print("Training is finished... The loss and accuracy values are: ")
print(results)

Epoch 1/10000
6/6 - 0s - loss: 0.0016 - accuracy: 1.0000 - 113ms/epoch - 19ms/step
Epoch 2/10000
6/6 - 0s - loss: 0.0019 - accuracy: 1.0000 - 4ms/epoch - 585us/step
Epoch 3/10000
6/6 - 0s - loss: 0.0017 - accuracy: 1.0000 - 3ms/epoch - 548us/step
Epoch 4/10000
6/6 - 0s - loss: 0.0015 - accuracy: 1.0000 - 4ms/epoch - 594us/step
Epoch 5/10000
6/6 - 0s - loss: 0.0016 - accuracy: 1.0000 - 3ms/epoch - 558us/step
Epoch 6/10000
6/6 - 0s - loss: 0.0014 - accuracy: 1.0000 - 3ms/epoch - 537us/step
Epoch 7/10000
6/6 - 0s - loss: 0.0015 - accuracy: 1.0000 - 3ms/epoch - 431us/step
Epoch 8/10000
6/6 - 0s - loss: 0.0015 - accuracy: 1.0000 - 3ms/epoch - 440us/step
Epoch 9/10000
6/6 - 0s - loss: 0.0015 - accuracy: 1.0000 - 3ms/epoch - 511us/step
Epoch 10/10000
6/6 - 0s - loss: 0.0014 - accuracy: 1.0000 - 4ms/epoch - 621us/step
Epoch 11/10000
6/6 - 0s - loss: 0.0016 - accuracy: 1.0000 - 4ms/epoch - 664us/step
Epoch 12/10000
6/6 - 0s - loss: 0.0012 - accuracy: 1.0000 - 3ms/epoch - 522us/step
Epoch 13/100